[package]
name = "karva_core"
version = "0.0.0"
edition = "2024"

[dependencies]
camino = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, optional = true }
tracing-tree = { workspace = true, optional = true }
