[package]
name = "karva_core"
version = "0.0.0"
edition = "2024"

[dependencies]
camino = { workspace = true }
pyo3 = { version = "0.24.2", features = ["auto-initialize"] }
serde = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, optional = true }
tracing-tree = { workspace = true, optional = true }

[dev-dependencies]
tempfile = "3.8"
